cabal-version: 3.0
name: haskell-json-cli-starter
version: 0.1.0.0
synopsis: A walking-skeleton starter for Haskell JSON CLI tools
homepage: https://github.com/sgillespie/haskell-json-cli-starter
license: MIT
license-file: LICENSE
author: Sean Gillespie
maintainer: sean@mistersg.net
copyright: 2026 Sean Gillespie
category: Text
build-type: Simple

common common-options
  ghc-options: -Wall
  build-depends:
    base <5,
    aeson,
    aeson-pretty,
    bytestring,
    containers,
    vector,
    text,

  default-extensions:
    DeriveAnyClass
    DerivingStrategies
    LambdaCase
    OverloadedStrings
    RecordWildCards

  default-language: GHC2021

library
  import: common-options
  exposed-modules: Lib
  hs-source-dirs: src

executable starter
  import: common-options
  main-is: Main.hs
  build-depends:
    haskell-json-cli-starter,
    optparse-applicative

  hs-source-dirs: app
  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

test-suite haskell-json-cli-starter-test
  import: common-options
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  build-depends:
    haskell-json-cli-starter
